2017/07/25 14:06:52 [error] 1070#1070: *372 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET /auth/facebook/callback?code=AQDpjXgg4Anw6sZmxkZK5RI9PY5Bj6eYzUye_23Q06O6Qyl0j0Df1juVtrZBnAJOirREH0iPBQqfgP2YTCDnWQ18Eptfd19lw2Gy8lQZ1leIwNIX30-0M4YwZyrHLv8vzGGj6vE-11fHdsbX7vy2h99c2xQZTTRlQ4SZbIL0eQsE1bIBrwvcN3QT_XErWbxSX7vkMtdTZkjhPijtbduCBJjSJ4ksdOkOGlwWl9Cex8rQK9rrHwX4WBSCABTUW1j9zT3g_9ozPT7_3QnApApF-rfWgrmL8xiZCVGSi03EeGKfLgM1gUkHM0tjsuuYK4lgrmMMgIBMcWFDC9XmQ0bohe3-&state=LkAmKdQXCvZcm00QkEavmvvBnqFfLhyLZnbT1W5M HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/login"
2017/07/25 16:46:23 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:24 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:25 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:25 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:26 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:31 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:32 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:32 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:54 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:55 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:46:55 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:47:09 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:47:09 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /BookExport HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/25 16:47:11 [error] 1069#1069: *1296 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:48:50 [error] 29004#29004: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /quanlykhach HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:48:52 [error] 29004#29004: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /quanlykhach HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:49:01 [error] 29039#29039: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /quanlykhach HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:49:08 [error] 29039#29039: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:49:11 [error] 29039#29039: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:49:13 [error] 29039#29039: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:50:51 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:50:52 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:50:52 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 16:50:54 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:54 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:54 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:54 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:55 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:55 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 16:50:55 [error] 29211#29211: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /Bookview/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/quanlykhach"
2017/07/25 17:04:33 [error] 30094#30094: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET /bookForm HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:06:22 [error] 4392#4392: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:11:36 [error] 5014#5014: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:20:26 [error] 5565#5565: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:26:47 [error] 6137#6137: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:39:22 [error] 7732#7732: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:39:23 [error] 7732#7732: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/25 18:39:23 [error] 7732#7732: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/26 15:37:40 [error] 1059#1059: *1756 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected protected (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected 'protected' (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/26 15:37:41 [error] 1059#1059: *1756 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected protected (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected 'protected' (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/26 15:37:42 [error] 1059#1059: *1756 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected protected (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected 'protected' (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/26 15:37:45 [error] 1059#1059: *1757 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected protected (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected 'protected' (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/26 15:37:48 [error] 1059#1059: *1757 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected protected (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected 'protected' (T_PROTECTED) in /var/www/html/blog/app/Exceptions/Handler.php on line 70
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:00:33 [error] 1062#1062: *68 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/07/27 19:00:35 [error] 1062#1062: *68 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:01:54 [error] 1065#1065: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:01:55 [error] 1065#1065: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:01:57 [error] 1065#1065: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:01:57 [error] 1065#1065: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/07/27 19:01:58 [error] 1065#1065: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare App\Http\Controllers\MyFirstController::Login() in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 130" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev"
2017/08/01 07:57:05 [error] 1056#1056: *1 directory index of "/var/www/html/blog/public/uploads/" is forbidden, client: 127.0.0.1, server: lara.dev, request: "GET /uploads/ HTTP/1.1", host: "lara.dev"
2017/08/01 10:16:19 [error] 1056#1056: *526 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET /updateinfoC/1?_token%20=%20KEWTja4GoggC4Q9OjkJRLfzOQcnxTXkvAf0TqX8T HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/khachview/1"
2017/08/01 15:23:37 [error] 1052#1052: *608 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET /getinfoB/79?_token%20=%20uiH2vy6tAqRzCKeRBRzY6SEbSRRXKrjy5fhp6U1H HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/08/01 15:34:38 [error] 1052#1052: *892 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET /updateinfoB/78?_token%20=%20uiH2vy6tAqRzCKeRBRzY6SEbSRRXKrjy5fhp6U1H HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/08/01 15:34:42 [error] 1052#1052: *897 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
Stack trace:
#0 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/html/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 112" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "GET /updateinfoB/78?_token%20=%20uiH2vy6tAqRzCKeRBRzY6SEbSRRXKrjy5fhp6U1H HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/Bookview/1"
2017/08/07 08:21:33 [error] 1051#1051: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use Illuminate\Http\Request as Request because the name is already in use in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 6" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "POST /mselect HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/uploadimg"
2017/08/07 08:21:35 [error] 1051#1051: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use Illuminate\Http\Request as Request because the name is already in use in /var/www/html/blog/app/Http/Controllers/MyFirstController.php on line 6" while reading response header from upstream, client: 127.0.0.1, server: lara.dev, request: "POST /mselect HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lara.dev", referrer: "http://lara.dev/uploadimg"
